########################################################################
# Yleiset asetukset
########################################################################

agentAddress udp:161

########################################################################
# AgentX
########################################################################

master agentx

agentXSocket /var/agentx/master

########################################################################
# SNMPv2c
########################################################################

rocommunity public default

########################################################################
# Järjestelmätiedot
########################################################################

sysLocation     HAMK Lab
sysContact      admin@example.com
sysName         R1

########################################################################
# View
########################################################################

view all included .1

########################################################################
# Access Control
########################################################################

rouser authPrivUser

########################################################################
# Ota kaikki MIB-haarat käyttöön
########################################################################

access notConfigGroup "" any noauth exact all none none